### ISSUE TITLE
where is the dmn_batch code ?

### ISSUE THREAD

**Issue by iamsile** [YerevaNN/Dynamic-memory-networks-in-Theano#1]
where is the dmn_batch code ? i couldn't find it the project

**Comment by Hrant-Khachatrian** [comment]
we found a bug in the implementation before releasing the code, so we skipped that file. We're working on that now

**Comment by iamsile** [comment]
thank you!

**Comment by hrayrhar** [comment]
We have fixed the dmn_batch code. 
We will be glad to hear some feedback about the code.

**Comment by iamsile** [comment]
@Harhro94 thank you very much!
