### ISSUE TITLE
Dynamic-memory-networks-in-Theano/data/en/all_shuffled_train.txt not found

### ISSUE THREAD

**Issue by philipperemy** [YerevaNN/Dynamic-memory-networks-in-Theano#3]
```
==> Loading test from /private/tmp/new/Dynamic-memory-networks-in-Theano/data/en/all_shuffled_train.txt
Traceback (most recent call last):
  File "api.py", line 73, in <module>
    babi_train_raw, babi_test_raw = dmn_utils.get_babi_raw('joint', 'joint')
  File "../utils.py", line 78, in get_babi_raw
    babi_train_raw = init_babi(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'data/en/%s_train.txt' % babi_name))
  File "../utils.py", line 8, in init_babi
    for i, line in enumerate(open(fname)):
IOError: [Errno 2] No such file or directory: '/private/tmp/new/Dynamic-memory-networks-in-Theano/data/en/all_shuffled_train.txt'
```

when running

```
python api.py
```

in 

```
server/
```

**Comment by Hrant-Khachatrian** [comment]
Here are the missing files, they can be easily generated by merging and shuffling all babi tasks. We forgot to add this in the data downloader. 
[all_shuffled_test.txt](https://github.com/YerevaNN/Dynamic-memory-networks-in-Theano/files/221735/all_shuffled_test.txt)
[all_shuffled_train.txt](https://github.com/YerevaNN/Dynamic-memory-networks-in-Theano/files/221745/all_shuffled_train.txt)

**Comment by philipperemy** [comment]
@Hrant-Khachatrian thank you very much. I wasn't sure as the shuffle could be different if I do it myself and if in some part of the code you kept this indexing, I would have had wrong results.
